@startuml
skinparam BackgroundColor transparent

title BDD for Styringsenhed

object "Styringsenhed" as styringsenhed
object "Lyd-modul" as lydmodul
object "Mikrofon" as mikrofon
object "Analog filterbehandlig" as filter
object "Joystick" as joystick
object "Central Computer IF" as centralComputerIF

styringsenhed *-- lydmodul
    lydmodul *-- mikrofon
    lydmodul *-- filter
styringsenhed *-- joystick
styringsenhed *-- centralComputerIF

@enduml