@startuml
skinparam BackgroundColor transparent

title BDD for SumoBot

object "SumoBot" as SumoBot
object "Motor" as Motor
object "Motorstyring" as Motorstyring
object "PSU" as PSU
object "Batteri" as Batteri
object "MicroController" as muc_SumoBot
object "Attack Sensor" as AttackSensor

SumoBot *-- Motor
  Motor *-- Motorstyring
SumoBot *-- PSU
  PSU *-- Batteri
SumoBot *-- muc_SumoBot
SumoBot *-- AttackSensor

@enduml
