@startuml

skinparam wrapWidth 200


class Display<<Boundary>>{
    +Display(int rows, int cols, int bits, int rs, int strb,int d0, int d1, int d2, int d3, int d4, int d5, int d6, int d7)
    +StartCountDown(int count)
    +LostLife(int player,&SumoBot,&SumoBot)
    +ShowWinner(int player)
    +writeToScreen(string msg)
    - _displayfd : int
	- _rows : int
	- _cols : int
	- _bits : int
	- _rs : int
	- _strb : int
	- _data[8] : int
}

@enduml