@startuml
skinparam BackgroundColor transparent

title BDD for SumoBot

object "SumoBot" as SumoBot
object "Motor" as Motor
object "Motorstyring" as Motorstyring
object "PSU" as PSU
object "Batteri" as Batteri
object "MicroController" as muc_SumoBot
object "Attack Sensor" as AttackSensor
object "Central Computer IF" as central_computer_IF

SumoBot *-- Motor
  Motor *-- Motorstyring
SumoBot *-- PSU
  PSU *-- Batteri
SumoBot *-- muc_SumoBot
SumoBot *-- AttackSensor
SumoBot *-- central_computer_IF

@enduml
