

all:
	arm-rpizw-g++ -lpthread -I/home/stud/SumoBot_Battle/E3PRJ3/Software/SumoBot/Tests/wiringPi *.cpp -lwiringPi -L/home/stud/SumoBot_Battle/E3PRJ3/Software/SumoBot/Tests -o Test_AttackSensorIF
clean:
	rm -f *.o ooc
