@startuml
title TCPServer::receiveMsg(char *buffer, int bufferLegth)
participant UC1
participant TCPServer

UC1 -> TCPServer : receiveMsg(buffer, bufferLenght)
TCPServer ->  TCPServer : bytesReceived = receiveMsg\n(clientSocket_, buffer, bufferLength, 0)
alt bytesReceived == -1
    UC1 <-- TCPServer : return -1 (received faild)
else bytesReceived == 0
    UC1 <-- TCPServer : return -2 (client disconnected)
end
note over TCPServer : prints received\nmessage

UC1 <-- TCPServer : return 0 (msg received in buffer)
@enduml