@startuml
participant UC1
participant TCPServer
participant TCPClient

UC1 -> TCPServer : closeServer(socket)
TCPServer -> TCPServer : "close socket"
alt Faild to cloes socket     
    UC1 <- TCPServer : return -1. "socket close faild"
else socket cloesed
    UC1 <- TCPServer : return 0. "socekt cloesed"
    TCPClient -> TCPClient : "lost connection to server"
end


@enduml