@startuml
participant UC1
participant TCPServer
participant hint
participant client

UC1 -> TCPServer : openServer(port)
TCPServer -> TCPServer : int listning = socket(AF_INET, SOCK_STREAM, 0);
note over TCPServer : creates a socket 
opt  listening == -1
    UC1 <-- TCPServer : return -1 (Socket faild to create))
end
note over hint : hint is object of struct sockaddr_in 
TCPServer -> hint ** : hint()
TCPServer -> hint : sin_family = AF_INET
TCPServer -> hint : sin_port = htons(port)
TCPServer -> TCPServer : inet_pton(AF_INET, "0.0.0.0", &hint.sin_addr)
TCPServer -> TCPServer : bind(listening, (sockaddr*)&hint, sizeof(hint));
TCPServer -> TCPServer : listen(listening, SOMAXCONN);


@enduml