# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\asha\Documents\PSoC3 training and projects\Q2-13\Alfonso_FFT\Alfonso_FFT.cydsn\Alfonso_FFT.cyprj
# Date: Fri, 31 May 2013 10:46:16 GMT
#set_units -time ns
create_clock -name {CyHFCLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CySYSCLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]


# Component constraints for C:\Users\asha\Documents\PSoC3 training and projects\Q2-13\Alfonso_FFT\Alfonso_FFT.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\asha\Documents\PSoC3 training and projects\Q2-13\Alfonso_FFT\Alfonso_FFT.cydsn\Alfonso_FFT.cyprj
# Date: Fri, 31 May 2013 10:46:03 GMT
