@startuml
title Startknap_Destructor

actor UC1 #Red
participant Startknap
actor OS #Red

UC1 -> Startknap : ~Startknap()
loop for all GPIO's
Startknap -> OS : Free GPIO1
OS --> Startknap : 
Startknap -> OS : Free GPIO2
OS --> Startknap : 
UC1 <-- Startknap :
destroy Startknap

@enduml