@startuml
title SumoBot Class diagram for UC1


class UC1 <<controller>>{
    +Run() : int
}

class Attacksensor<<Boundary>>{
    -attackStatus_ : int
    +getAttackStatus() : bool 
}

class Motor <<Boundary>>{
    +setDirSpeed(char *speedDir) : void
}
class CentralComputerIF <<Boundary>>{
    -_dir : int
    -_speed : int
    +getDirSpeed() : char[]
}

CentralComputerIF -- UC1
UC1 -- Motor
UC1 - Attacksensor

@enduml
