@startuml
title SumoBot Class diagram for UC1


class UC1 <<controller>>{
    -*ASIF_ : AttacksensorIF
    -*CCIF_ : CentralComputerIF
    -*MSIF_ : MotorstyringIF
    +UC1(string, string, string, int)
    +~UC1()
    +Run() : void
}

class AttacksensorIF<<Boundary>>{
    -attackStatus_ : int
    +getAttackStatus() : bool 
}

class MotorstyringIF <<Boundary>>{
    +setSpeedDir(char *speedDir) : void
}
class CentralComputerIF <<Boundary>>{
    -*_TCPC : TCPClient
    +CentralComputerIF(string, string, string, string, int)
    +~CentralComputerIF()
    +getDirSpeed(string, char*, int) : char*
}

CentralComputerIF -- UC1
UC1 -- MotorstyringIF
UC1 - AttacksensorIF

@enduml
