@startuml
title Wifi::createHotspot()
participant UC1
participant Wifi
actor OS #red
actor Connman #red

UC1 -> Wifi : createHotspot(SSID,passphrase)
Wifi -> Wifi : SSID_ = SSID\npassphrase_ = passphrase\nint err = 0
Wifi -> OS : err = echo SSID=SSID_>/etc/connman-hotspot.conf\nerr = echo PASSWORD=passphrase_>>/etc/connman-hotspot.conf
OS -> Connman : update SSID, \npassphrase
OS <-- Connman
opt err == -1 || err == 127
Wifi <-- OS : return -1 | 127
UC1 <-- Wifi : return -1 (faild to set \nSSID, passphrase)
end
Wifi <-- OS

Wifi -> OS : connman-hotspot enable
OS -> Connman : connman-hotspot enable
OS <-- Connman
opt err == -1 || err == 127
Wifi <-- OS : return -1 | 127
UC1 <-- Wifi : return -2 (faild to create hotspot)
end
Wifi <-- OS
UC1 <-- Wifi : return 0

@enduml