@startuml
title Wifi::createHotspot()
participant UC1
participant Wifi
actor OS #red
actor Connman #red

UC1 -> Wifi : createHotspot(SSID,passphrase)
Wifi -> Wifi : SSID_ = SSID, passphrase_ = passphrase
Wifi -> OS : echo SSID=SSID_>/etc/connman-hotspot.conf
OS -> Connman : update SSID
OS <-- Connman
Wifi <-- OS

Wifi -> OS : echo PASSWORD=passphrase_>>/etc/connman-hotspot.conf
OS -> Connman : update PASSWORD
OS <-- Connman
Wifi <-- OS

Wifi -> OS : connman-hotspot enable
OS -> Connman : connman-hotspot enable
OS <-- Connman
Wifi <-- OS

@enduml