@startuml
title Wifi::connectToWifi()
participant UC1
participant Wifi
actor Connman #red

UC1 -> Wifi : connectToWifi(SSID,passphrase,MAC)
Wifi -> Wifi : "save SSID, passphrase and MAC"
Wifi -> Connman : scan wifi
Connman -> Connman : "scannign wifi"
alt Scaning faild
    Connman --> Wifi : "scanning faild"
    Wifi --> UC1 : return -1. "scanning faild"
else Scanning complete
    Connman --> Wifi : "scanning complete"
end
    


Wifi -> Wifi : "convert SSID to Hex value"
Wifi -> Connman : connect(MAC, SSIDHexValue)
Connman -> Connman : "connecting to Hotspot"
alt connection faild
    Connman --> Wifi : "connection faild"
    Wifi --> UC1 : return -2. "connection faild"
else
    Connman --> Wifi : "connected"

    
     
Connman --> Wifi : "enter passphrase"
Wifi -> Connman : passphrase
Connman -> Connman : "evaluating passphrase"
opt wrong passphrase
    Connman --> Wifi : "wrong passphrase"
    Wifi --> UC1 : return - 3 "wrong passphrase"
end
Connman --> Wifi : "connected"
Wifi --> UC1 : return 0. "connected"

@enduml