@startuml
participant UC1
participant Wifi
actor Connman #red

UC1 -> Wifi : createHotspot(SSID,passphrase)
Wifi -> Wifi : "save SSID and passphrase"
Wifi -> Connman : changeSSIDPassword(SSID, passphrase)
Connman -> Connman : "changeing SSID and password"
opt changeing faild
    Connman --> Wifi : "change faild"
    Wifi --> UC1 : return -1. "change faild"
end
Wifi -> Connman : hotspot(enable)
Connman -> Connman : "enable hotspot"
opt faild to enable hotspot
    Connman --> Wifi : "faild to enable hotspot"
    Wifi --> UC1 : return -2. "faild to enable hotspot"
end

@enduml