@startuml
title Wifi::connectToWifi()
participant UC1
participant Wifi
actor OS #red
actor Connman #red

UC1 -> Wifi : connectToWifi(SSID, passphrase, MAC)

Wifi -> Wifi : SSID_ = SSID, MAC_ = MAC
Wifi -> Wifi : passphrase_ = passphrase
Wifi -> OS : connmanctl scan wifi

OS -> Connman : scan wifi
OS <-- Connman 
opt 
    Wifi <-- OS : return -1 || 127
    UC1 <-- Wifi : return -1 (scan faild)
end 
Wifi <-- OS

Wifi -> Wifi : SSID_hex = TextToHex(SSID_) 
note over Wifi : converting SSID to Hex value.

Wifi -> OS : connmanctl connect wifi_MAC_SSID_hex_managed_psk
OS -> Connman : connect wifi_MAC_SSID_hex_managed_psk
OS <-- Connman 
opt 
    Wifi <-- OS : return -1 || 127 
    UC1 <-- Wifi : return -2 (connect faild)
end 
Wifi <-- OS

Wifi -> OS :  echo passphrase
OS -> Connman : passphrase
OS <-- Connman 
opt 
    Wifi <-- OS : return -1 || 127 
    UC1 <-- Wifi : return -3 (passphrase faild)
end 
Wifi <-- OS
UC1 <-- Wifi : return 0 (connected)

@enduml