@startuml
title Wifi::closeHotspot()
participant UC1
participant Wifi
actor Linux #red
actor Connman #red

UC1 -> Wifi : closeHotspot()
Wifi -> Linux : connman-hotspot disable
Linux -> Connman : connman-hotspot disable
Linux <-- Connman
opt faild to disable hotspot
    Linux --> Wifi : return -1 | 127
    Wifi --> UC1 : return -1. (faild to disable hotspot)
end
UC1 <- Wifi : return 0 (hotspot diabled)

@enduml