@startuml
title Wifi::closeHotspot()
participant UC1
participant Wifi
actor OS #red
actor Connman #red

UC1 -> Wifi : closeHotspot()
Wifi -> OS : connman-hotspot disable
OS -> Connman : connman-hotspot disable
OS <-- Connman
opt faild to disable hotspot
    OS --> Wifi : return -1 | 127
    Wifi --> UC1 : return -1. (faild to disable hotspot)
end
UC1 <-- Wifi : return 0 (hotspot diabled)

@enduml