

all:
	arm-rpizw-g++ -lpthread -I/home/stud/SumoBot_Battle/E3PRJ3/Software/SumoBot/Projekt/SumoBot/wiringPi *.cpp -lwiringPi -L/home/stud/SumoBot_Battle/E3PRJ3/Software/SumoBot/Projekt/SumoBot -o Test_SumoBot_RPI
clean:
	rm -f *.o ooc
