@startuml
title CD_UC1

skinparam wrapWidth 200

class UC1 <<controller>>{
    +UC1(Startknap* SK, Display *D)
    +Run()
    +~UC1()
    -Startknap* _SK
    -Display* _D
    -Player _player[2]
}

class Startknap <<Domain>>{
-_gpio[2] : int
-_Status[2] : bool
+Startknap(int gpio1, int gpio2)
+WaitForStart()
+~Startknap()

}

class Display<<Boundary>>{
    +Display(int rows, int cols, int bits, int rs, int strb,int d0, int d1, int d2, int d3, int d4, int d5, int d6, int d7)
    +StartCountDown(int count)
    +LostLife(int player,&SumoBot,&SumoBot)
    +ShowWinner(int player)
    +writeToScreen(string msg)
    - _displayfd : int
	- _rows : int
	- _cols : int
	- _bits : int
	- _rs : int
	- _strb : int
	- _data[8] : int
}

class SumoBot <<Boundary>>{
    - _TCPS : TCPServer*
    - _lifes : int
    -_retning : int
    -_speed : int
    -_attackStatus : bool

    +SumoBot(int lifes, int player)
    +SetDirectionAndSpeed(int dir,int speed)
    +SubstractLife()
    +GetLives()
    +~SumoBot()
}
class Styringsenhed <<Boundary>>{
    -_speed : int
    -_direction : int
    -_SPIM : SPIMaster* 
    +Styringsenhed(int channel, int comSpeed, int bufferSize)
    +GetDirectionAndSpeed(int &dir, int &speed)
    +Styringsenhed()
}

class Player <<Struct>> {
direction : int
speed : int
life : int
attack : bool 
SBptr : SumoBot*
SEptr : Styringsenhed*
hide members
show fields
}
hide <<Struct>> circle

Startknap"2" -- UC1
UC1 -- "2"Styringsenhed
UC1 - "2"SumoBot
Display - UC1

@enduml