@startuml
title CC Class diagram for UC1


class UC1 <<controller>>{
    Run()
}

class Startknap <<Domain>>{
bool Status
WaitForStart()
}
class Display<<Boundary>>{
    StartCountDown(int count)
    LostLife(&SumoBot,&SumoBot)
    ShowWinner(&SumoBot)
}

class SumoBot <<Boundary>>{
    int Liv
    float Retning
    int Hastighed
    bool AttackStatus
    SetDirectionAndSpeed(Dir,Speed)
    SubstractLife()
    GetLives()
}
class Styringsenhed <<Boundary>>{
    float Retning
    int Hastighed
    GetDirectionAndSpeed()
}

Startknap"2" -- UC1
UC1 -- "2"Styringsenhed
UC1 - "2"SumoBot
Display - UC1

@enduml