

all: 
	arm-rpizw-g++ -lpthread -I/home/stud/E3PRJ3/Software/CentralComputer/wiringPi *.cpp -lwiringPi -L/home/stud/E3PRJ3/Software/CentralComputer -o Test_CC
#	arm-rpizw-g++ -lpthread -I/home/stud/E3PRJ3/Software/CentralComputer/wiringPi Test_SB.cpp -lwiringPi -L/home/stud/E3PRJ3/Software/CentralComputer -o Test_SB

clean:
	rm -f *.o ooc
