@startuml
title SumoBot Class diagram for UC1


class UC1 <<controller>>{
    +Run() : int
}

class Attacksensor<<Boundary>>{
    -attackStatus : int
    +getAttackStatus() : bool 
}

class Motor <<Boundary>>{
    -dir : int
    -speed : int
    +setDirSpeed() : void
}
class CentralComputerIF <<Boundary>>{
    -dir : int
    -speed : int
    +getDirSpeed() : int
}

CentralComputerIF -- UC1
UC1 -- Motor
UC1 - Attacksensor

@enduml
