function Hd = tuk200_350
%TUK200_350 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
% Generated on: 11-Dec-2020 17:07:55

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 10000;  % Sampling Frequency

N     = 134;       % Order
Fc1   = 200;      % First Cutoff Frequency
Fc2   = 350;      % Second Cutoff Frequency
flag  = 'scale';  % Sampling Flag
Alpha = 0.1;        % Window Parameter
% Create the window vector for the design algorithm.
win = tukeywin(N+1, Alpha);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
